# Generated by Django 5.2.1 on 2025-05-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("institution", models.CharField(max_length=200)),
                ("completion_date", models.DateField()),
                ("description", models.TextField(blank=True)),
                ("certificate_url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                (
                    "experience_type",
                    models.CharField(
                        choices=[
                            ("work", "Work Experience"),
                            ("volunteer", "Volunteer"),
                            ("internship", "Internship"),
                            ("freelance", "Freelance"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("description", models.TextField()),
                (
                    "skills_used",
                    models.CharField(
                        help_text="Comma-separated skills", max_length=500
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="PersonalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("location", models.CharField(max_length=100)),
                ("bio", models.TextField()),
                ("profile_image", models.ImageField(blank=True, upload_to="profile/")),
                ("resume_file", models.FileField(blank=True, upload_to="resume/")),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "technologies",
                    models.CharField(
                        help_text="Comma-separated technologies", max_length=300
                    ),
                ),
                ("github_url", models.URLField(blank=True)),
                ("live_url", models.URLField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="projects/")),
                ("featured", models.BooleanField(default=False)),
                ("created_date", models.DateField()),
            ],
            options={
                "ordering": ["-created_date"],
            },
        ),
    ]
