# Generated by Django 5.2.1 on 2025-05-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personalinfo",
            name="resume_file",
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="education",
            field=models.CharField(default="Bachelor's Degree", max_length=100),
        ),
        migrations.AlterField(
            model_name="experience",
            name="experience_type",
            field=models.CharField(
                choices=[
                    ("work", "Work Experience"),
                    ("volunteer", "Volunteer"),
                    ("internship", "Internship"),
                    ("freelance", "Freelance"),
                    ("Conference/Summit", "Conference/Summit"),
                ],
                max_length=20,
            ),
        ),
    ]
