# Generated by Django 5.2.1 on 2025-05-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_remove_personalinfo_resume_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalinfo",
            name="education",
            field=models.CharField(max_length=100),
        ),
    ]
